title: sporadic
description: "Composable Concurrency Abstractions for JavaScript."
theme: jekyll-theme-slate
repository: marcoonroad/sporadic
show_downloads: false
google_analytics: UA-41209773-2
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
